# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11 adopt
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
    - name: Compile hello
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: hello
    - name: Compile junit5
      run: mvn -B test --file pom.xml
      working-directory: junit5
    - name: Compile arquillian
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: arquillian
    - name: Compile cdi
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: cdi
    - name: Compile jpa-entity
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: jpa-entity
    - name: Compile jpa-relations
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: jpa-relations
    - name: Compile jpa-dao
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: jpa-dao
    - name: Compile jpa-query
      run: mvn -B package --file pom.xml -DskipTests
      working-directory: jpa-query